### ISSUE TITLE
连接怪兽不能作为连接魔法在魔陷区安置

### ISSUE THREAD

**Issue by wyykak** [purerosefallen/ygopro-core#6]
由于card::get_link_marker()（card.cpp:1258）在处理连接怪兽时，如果检测到其位于魔陷区就直接返回0，导致即使注册了EFFECT_LINK_SPELL_KOISHI效果也不能作为连接魔法生成连接区。请问这是预期的行为吗？

**Comment by purerosefallen** [comment]
62a5cb6
